pipeline {
    agent {
        kubernetes {
            label 'maven'
            defaultContainer 'maven'
            namespace 'cje-support-agents'
        }
    }

    stages {
        stage('Checkout') { 
            steps {
                git credentialsId: "${github_creds}", url: "${github_repo}"
            }
        }
        stage('Build') { 
            steps {
                sh 'mvn -Dmaven.test.failure.ignore=true install'
            }
        }
    }

    post {
        success {
            junit allowEmptyResults: true, testResults: "target/surefire-reports/*.xml"
        }
    }
}
